parameters:
    realisations:
        agrandissement_maison:
            title: Agrandissement de maison
            pictures:
                - realisations/agrandissement_maison/agrandissement-1.jpg
                - realisations/agrandissement_maison/agrandissement-2.jpg
                - realisations/agrandissement_maison/agrandissement-3.jpg
                - realisations/agrandissement_maison/agrandissement-4.jpg
                - realisations/agrandissement_maison/agrandissement-5.jpg
        charpente:
            title: Charpentes
            pictures:
                - realisations/charpentes/IMG_0299.jpg
                - realisations/charpentes/IMG_0303.jpg
                - realisations/charpentes/IMG_0387.jpg
                - realisations/charpentes/IMG_0389.jpg
                - realisations/charpentes/IMG_0390.jpg
                - realisations/charpentes/IMG_0391.jpg
                - realisations/charpentes/IMG_0396.jpg
                - realisations/charpentes/IMG_0397.jpg
                - realisations/charpentes/IMG_0398.jpg
                - realisations/charpentes/IMG_0399.jpg
                - realisations/charpentes/IMG_0407.jpg
                - realisations/charpentes/IMG_0410.jpg
                - realisations/charpentes/IMG_0412.jpg
                - realisations/charpentes/IMG_0414.jpg
                - realisations/charpentes/IMG_0416.jpg
                - realisations/charpentes/IMG_0417.jpg
                - realisations/charpentes/IMG_0418.jpg
                - realisations/charpentes/IMG_0419.jpg
                - realisations/charpentes/IMG_0420.jpg
                - realisations/charpentes/IMG_0437.jpg
                - realisations/charpentes/IMG_0438.jpg
                - realisations/charpentes/IMG_0439.jpg
                - realisations/charpentes/IMG_0440.jpg
                - realisations/charpentes/IMG_0830.jpg
                - realisations/charpentes/IMG_0854.jpg
                - realisations/charpentes/IMG_0855.jpg
                - realisations/charpentes/IMG_0863.jpg
                - realisations/charpentes/IMG_1092.jpg
                - realisations/charpentes/IMG_1144.jpg
                - realisations/charpentes/IMG_1151.jpg
                - realisations/charpentes/IMG_1153.jpg
                - realisations/charpentes/IMG_2084.jpg
                - realisations/charpentes/IMG_2085.jpg
                - realisations/charpentes/IMG_2086.jpg
                - realisations/charpentes/IMG_2087.jpg
                - realisations/charpentes/thumb_P1020040_1024.jpg
                - realisations/charpentes/thumb_P1020041_1024.jpg
                - realisations/charpentes/thumb_P1020046_1024.jpg
                - realisations/charpentes/thumb_P1020050_1024.jpg
                - realisations/charpentes/thumb_P1020055_1024.jpg
                - realisations/charpentes/thumb_P1020056_1024.jpg
                - realisations/charpentes/thumb_P1020112_1024.jpg
        mobilier:
            title: Mobilier
            pictures:
                - realisations/mobilier/buffet-1.jpg
                - realisations/mobilier/bureau-1.jpg
                - realisations/mobilier/jardiniere-1.jpg
                - realisations/mobilier/meuble-tv-1.jpg
                - realisations/mobilier/table-1.jpg
                - realisations/mobilier/table-basse-1.jpg
                - realisations/mobilier/table-basse-2.jpg
                - realisations/mobilier/transat-bamboo-1.jpg
        esscalier:
            title: Escalier
            pictures:
                - realisations/escalier/escalier-1.jpg
                - realisations/escalier/escalier-2.jpg
                - realisations/escalier/escalier-3.jpg
        garde_corps:
            title: Garde Corps
            pictures:
                - realisations/garde-corps/garde-corps-1.jpg
                - realisations/garde-corps/garde-corps-2.jpg
                - realisations/garde-corps/garde-corps-3.jpg
                - realisations/garde-corps/garde-corps-4.jpg
                - realisations/garde-corps/garde-corps-5.jpg
        isolation:
            title: Isolation
            pictures:
                - realisations/isolation/isolation-1.jpg
                - realisations/isolation/isolation-2.jpg
                - realisations/isolation/isolation-3.jpg
                - realisations/isolation/isolation-4.jpg
                - realisations/isolation/isolation-5.jpg
        pose:
            title: Pose
            pictures:
                - realisations/cuisine/cuisine.jpg
        terrasse:
            title: Terrasse et abri de jardin
            pictures:
                - realisations/terrasse-abri-de-jardin/abri-jardin-1.jpg
                - realisations/terrasse-abri-de-jardin/IMG_1921.jpg
                - realisations/terrasse-abri-de-jardin/IMG_1922.jpg
                - realisations/terrasse-abri-de-jardin/IMG_2202.jpg
                - realisations/terrasse-abri-de-jardin/IMG_2203.jpg
                - realisations/terrasse-abri-de-jardin/IMG_2225.jpg
                - realisations/terrasse-abri-de-jardin/IMG_2227.jpg
                - realisations/terrasse-abri-de-jardin/IMG_2334.jpg
                - realisations/terrasse-abri-de-jardin/IMG_2335.jpg
                - realisations/terrasse-abri-de-jardin/IMG_2336.jpg
                - realisations/terrasse-abri-de-jardin/IMG_2342.jpg
                - realisations/terrasse-abri-de-jardin/thumb_P1020211_1024.jpg
                - realisations/terrasse-abri-de-jardin/thumb_P1020213_1024.jpg
        autre:
            title: Divers
            pictures:
                - realisations/pont/passage.jpg
                - realisations/pont/pont.jpg
                - realisations/croix/croix-1.jpg
                - realisations/croix/croix-2.jpg

