parameters:
    realisations:
        agrandissement_maison:
            title: Agrandissement de maison
            pictures:
                - agrandissement_maison/agrandissement-1.jpg
                - agrandissement_maison/agrandissement-2.jpg
                - agrandissement_maison/agrandissement-3.jpg
                - agrandissement_maison/agrandissement-4.jpg
                - agrandissement_maison/agrandissement-5.jpg
        charpente:
            title: Charpentes
            pictures:
                - charpentes/IMG_0299.jpg
                - charpentes/IMG_0303.jpg
                - charpentes/IMG_0387.jpg
                - charpentes/IMG_0389.jpg
                - charpentes/IMG_0390.jpg
                - charpentes/IMG_0391.jpg
                - charpentes/IMG_0396.jpg
                - charpentes/IMG_0397.jpg
                - charpentes/IMG_0398.jpg
                - charpentes/IMG_0399.jpg
                - charpentes/IMG_0407.jpg
                - charpentes/IMG_0410.jpg
                - charpentes/IMG_0412.jpg
                - charpentes/IMG_0414.jpg
                - charpentes/IMG_0416.jpg
                - charpentes/IMG_0417.jpg
                - charpentes/IMG_0418.jpg
                - charpentes/IMG_0419.jpg
                - charpentes/IMG_0420.jpg
                - charpentes/IMG_0437.jpg
                - charpentes/IMG_0438.jpg
                - charpentes/IMG_0439.jpg
                - charpentes/IMG_0440.jpg
                - charpentes/IMG_0830.jpg
                - charpentes/IMG_0854.jpg
                - charpentes/IMG_0855.jpg
                - charpentes/IMG_0863.jpg
                - charpentes/IMG_1092.jpg
                - charpentes/IMG_1144.jpg
                - charpentes/IMG_1151.jpg
                - charpentes/IMG_1153.jpg
                - charpentes/IMG_2084.jpg
                - charpentes/IMG_2085.jpg
                - charpentes/IMG_2086.jpg
                - charpentes/IMG_2087.jpg
                - charpentes/thumb_P1020040_1024.jpg
                - charpentes/thumb_P1020041_1024.jpg
                - charpentes/thumb_P1020046_1024.jpg
                - charpentes/thumb_P1020050_1024.jpg
                - charpentes/thumb_P1020055_1024.jpg
                - charpentes/thumb_P1020056_1024.jpg
                - charpentes/thumb_P1020112_1024.jpg
        mobilier:
            title: Mobilier
            pictures:
                - mobilier/buffet-1.jpg
                - mobilier/bureau-1.jpg
                - mobilier/jardiniere-1.jpg
                - mobilier/meuble-tv-1.jpg
                - mobilier/table-1.jpg
                - mobilier/table-basse-1.jpg
                - mobilier/table-basse-2.jpg
                - mobilier/transat-bamboo-1.jpg
        esscalier:
            title: Escalier
            pictures:
                - escalier/escalier-1.jpg
                - escalier/escalier-2.jpg
                - escalier/escalier-3.jpg
        garde_corps:
            title: Garde Corps
            pictures:
                - garde-corps/garde-corps-1.jpg
                - garde-corps/garde-corps-2.jpg
                - garde-corps/garde-corps-3.jpg
                - garde-corps/garde-corps-4.jpg
        isolation:
            title: Isolation
            pictures:
                - isolation/isolation-1.jpg
                - isolation/isolation-2.jpg
                - isolation/isolation-3.jpg
                - isolation/isolation-4.jpg
                - isolation/isolation-5.jpg
        pose:
            title: Pose
            pictures:
                - cuisine/cuisine.jpg
        terrasse:
            title: Terrasse et abri de jardin
            pictures:
                - terrasse-abri-de-jardin/abri-jardin-1.jpg
                - terrasse-abri-de-jardin/IMG_1921.jpg
                - terrasse-abri-de-jardin/IMG_1922.jpg
                - terrasse-abri-de-jardin/IMG_2202.jpg
                - terrasse-abri-de-jardin/IMG_2203.jpg
                - terrasse-abri-de-jardin/IMG_2225.jpg
                - terrasse-abri-de-jardin/IMG_2227.jpg
                - terrasse-abri-de-jardin/IMG_2334.jpg
                - terrasse-abri-de-jardin/IMG_2335.jpg
                - terrasse-abri-de-jardin/IMG_2336.jpg
                - terrasse-abri-de-jardin/IMG_2342.jpg
                - terrasse-abri-de-jardin/thumb_P1020211_1024.jpg
                - terrasse-abri-de-jardin/thumb_P1020213_1024.jpg
        autre:
            title: Divers
            pictures:
                - pont/passage.jpg
                - pont/pont.jpg
                - croix/croix-1.jpg

